spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db2?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    # /static/ ?? ???? ??? ?? ?? ?? ??
    static-path-pattern: /static/**
  web:
    resources:
      # ?? ?? ?? ??
      static-locations: file:media/,classpath:/static
jwt:
  secret: aaaabbbsdifqbvaesoioegwaaaabbbsdifqbvaesoioegwaaaabbbsdifqbvaesasdfqve